apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      serviceAccountName: {{ .Values.name }}
      containers:
        - name: {{ .Values.name }}
          image: {{ .Values.image }}
          imagePullPolicy: {{ .Values.imagepull }}
          env:
          - name: GROUP
            value: {{ .Values.group }}
          - name: VERSION
            value: {{ .Values.version }}
          - name: PLURAL
            value: {{ .Values.plural }}
          - name: NAME
            value: {{ .Values.name }}
          - name: NAMESPACE
            value: {{ .Values.namespace }}
          - name: MOUNTER
            value: {{ quote .Values.mounter }}
          ports:
          - containerPort: 9867
---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  labels:
    app: {{ .Values.name }}
spec:
  ports:
  - port: {{ .Values.port }}
    targetPort: 9867
    protocol: TCP
  selector:
    app: {{ .Values.name }}


